steps:
# Install OpenTofu CLI
- id: install-tofu
  name: 'alpine'
  entrypoint: sh
  args:
    - '-c'
    - |
      wget https://github.com/opentofu/opentofu/releases/download/v1.6.0/tofu_1.6.0_linux_amd64.zip &&
      unzip tofu_1.6.0_linux_amd64.zip &&
      mv tofu /usr/local/bin/ &&
      chmod +x /usr/local/bin/tofu

# Initialize OpenTofu (with remote backend)
- id: init-tofu
  name: 'hashicorp/terraform'
  entrypoint: 'tofu'
  args: ['init']

# Apply configuration (Create clusters)
- id: apply-tofu
  name: 'hashicorp/terraform'
  entrypoint: 'tofu'
  args:
    - 'apply'
    - '-auto-approve'

# Read duration from env file and sleep for that duration (seconds)
- id: wait-duration
  name: 'alpine'
  entrypoint: sh
  args:
    - '-c'
    - |
      DURATION=$(grep DURATION duration.env | cut -d '=' -f2) &&
      echo "Sleeping for $DURATION seconds..." &&
      sleep $DURATION

# Destroy clusters after waiting period ends
- id: destroy-tofu
  name: 'hashicorp/terraform'
  entrypoint: 'tofu'
  args:
    - 'destroy'
    - '-auto-approve'
