steps:
  # Define Environment Variables and Terraform Initialization Step
  - name: 'hashicorp/terraform:latest'
    dir: 'terraform-provision-gke-cluster'
    env:
      - 'TF_VAR_PROJECT_ID=$PROJECT_ID'
      - 'TF_VAR_REGION=asia-south1'
      - 'TF_VAR_GKE_USERNAME=""'
      - 'TF_VAR_GKE_PASSWORD=""'
      - 'TF_VAR_GKE_NUM_NODES=1'
    args: ['init']

  # Terraform Plan Step
  - name: 'hashicorp/terraform:latest'
    dir: 'terraform-provision-gke-cluster'
    env:
      - 'TF_VAR_PROJECT_ID=$PROJECT_ID'
      - 'TF_VAR_REGION=asia-south1'
      - 'TF_VAR_GKE_USERNAME=""'
      - 'TF_VAR_GKE_PASSWORD=""'
      - 'TF_VAR_GKE_NUM_NODES=1'
    args: ['plan', '-out=terraform-plan.out']

  # Save Terraform Plan to Logs Bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - 'cp'
      - 'terraform-provision-gke-cluster/terraform-plan.out'
      - 'gs://ltc-hack-prj-19-cloud-build-logs/${BUILD_ID}/terraform-plan.out'

  # Optional: Apply the Terraform plan (Uncomment if you want to apply it)
  # - name: 'hashicorp/terraform:latest'
  #   dir: 'terraform-provision-gke-cluster'
  #   args: ['apply', '-auto-approve', 'terraform-plan.out']
  #   env:
  #     - 'TF_VAR_PROJECT_ID=$PROJECT_ID'
  #     - 'TF_VAR_REGION=asia-south1'
  #     - 'TF_VAR_GKE_USERNAME=""'
  #     - 'TF_VAR_GKE_PASSWORD=""'
  #     - 'TF_VAR_GKE_NUM_NODES=1'

logsBucket: 'gs://ltc-hack-prj-19-cloud-build-logs/${BUILD_ID}'

options:
  logging: GCS_ONLY

serviceAccount: 'projects/ltc-hack-prj-19/serviceAccounts/local-resource-creator@ltc-hack-prj-19.iam.gserviceaccount.com'
